const BOOK_MAP: Record<string, string> = {
  'Genesis': '01_Genesis',
  'Exodus': '02_Exodus',
  'Leviticus': '03_Leviticus',
  'Numbers': '04_Numbers',
  'Deuteronomy': '05_Deuteronomy',
  'Joshua': '06_Joshua',
  'Judges': '07_Judges',
  'Ruth': '08_Ruth',
  '1 Samuel': '09_1Samuel',
  '2 Samuel': '10_2Samuel',
  '1 Kings': '11_1Kings',
  '2 Kings': '12_2Kings',
  '1 Chronicles': '13_1Chronicles',
  '2 Chronicles': '14_2Chronicles',
  'Ezra': '15_Ezra',
  'Nehemiah': '16_Nehemiah',
  'Esther': '17_Esther',
  'Job': '18_Job',
  'Psalms': '19_Psalms',
  'Proverbs': '20_Proverbs',
  'Ecclesiastes': '21_Ecclesiastes',
  'Song of Songs': '22_SongofSongs',
  'Isaiah': '23_Isaiah',
  'Jeremiah': '24_Jeremiah',
  'Lamentations': '25_Lamentations',
  'Ezekiel': '26_Ezekiel',
  'Daniel': '27_Daniel',
  'Hosea': '28_Hosea',
  'Joel': '29_Joel',
  'Amos': '30_Amos',
  'Obadiah': '31_Obadiah',
  'Jonah': '32_Jonah',
  'Micah': '33_Micah',
  'Nahum': '34_Nahum',
  'Habakkuk': '35_Habakkuk',
  'Zephaniah': '36_Zephaniah',
  'Haggai': '37_Haggai',
  'Zechariah': '38_Zechariah',
  'Malachi': '39_Malachi',
  'Matthew': '40_Matthew',
  'Mark': '41_Mark',
  'Luke': '42_Luke',
  'John': '43_John',
  'Acts': '44_Acts',
  'Romans': '45_Romans',
  '1 Corinthians': '46_1Corinthians',
  '2 Corinthians': '47_2Corinthians',
  'Galatians': '48_Galatians',
  'Ephesians': '49_Ephesians',
  'Philippians': '50_Philippians',
  'Colossians': '51_Colossians',
  '1 Thessalonians': '52_1Thessalonians',
  '2 Thessalonians': '53_2Thessalonians',
  '1 Timothy': '54_1Timothy',
  '2 Timothy': '55_2Timothy',
  'Titus': '56_Titus',
  'Philemon': '57_Philemon',
  'Hebrews': '58_Hebrews',
  'James': '59_James',
  '1 Peter': '60_1Peter',
  '2 Peter': '61_2Peter',
  '1 John': '62_1John',
  '2 John': '63_2John',
  '3 John': '64_3John',
  'Jude': '65_Jude',
  'Revelation': '66_Revelation',
};

export function bibleUrl(book: string, chapter: number): string {
  const key = BOOK_MAP[book];
  if (!key) return 'https://text.recoveryversion.bible/RcV.htm';
  return `https://text.recoveryversion.bible/${key}_${chapter}.htm`;
}
